### ISSUE TITLE
ESPHome 2026.8.2 build failure in dallasng_component.cpp

### ISSUE THREAD

**Issue by ForrestOK20** [nrandell/dallasng#25]
Hello,

after upgrading to ESPHome 2026.8.2, dallasng no longer compiles.

The build fails in:

C++
1
esphome/components/dallasng/dallasng_component.cpp:105
Zobrazit více řádků

with:

Plain Text
1
error: no matching function for call to
2
'esphome::dallasng::DallasNgComponent::set_timeout(
3
const std::string, uint16_t, lambda)'
4
 
Zobrazit více řádků

Current code:

C++
1
set_timeout(sensor->get_address_name(),
2
sensor->millis_to_wait_for_conversion(),
3
[this, sensor] {
Zobrazit více řádků

ESPHome now expects:

C++
1
void set_timeout(const char *name,
2
uint32_t timeout,
3
std::function<void()> &&f);
Zobrazit více řádků

and the compiler reports:

Plain Text
1
no known conversion for argument 1 from
2
'const std::string' to 'const char *'
Zobrazit více řádků

It looks like sensor->get_address_name() returns a std::string and may need:

C++
1
sensor->get_address_name().c_str()
Zobrazit více řádků

to compile with ESPHome 2026.8.2.

The issue is reproducible on multiple devices.

Thanks for maintaining this component.

Best regards Ondřej
